### ISSUE TITLE
测试自己的手写pkl 档却读取不到

### ISSUE THREAD

**Issue by chiaoooo** [dailenson/SDT#38]
近期在研究您的论文 SDT，我也想试着生成我的手写体。我已经将手写图片调整成64x64大小，并储存为 .pkl 档案。看了 issue 我想接下来要做的是将我的 .pkl 档放入 test_style_samples，并将 writer_dict.pkl 做修改，但这部分我并没有成功。

我的步骤是：将我的.pkl 档命名为006.pkl，然后把writer_dict.pkl 的"test_writer": {"006.pot": 0} 改成这样，我理想中这样应该只会生成我的字体，其他writer 的手写体就不会被生成，但我在执行时就会出现抓不到其他writer.pkl 档案的错误，如下：
Traceback (most recent call last):
  File "/home/vcpuser/SDT/test.py", line 118, in <module>
    main(opt)
  File "/home/vcpuser/SDT/test.py", line 59, in main
    for data in tqdm.tqdm(test_loader):
  File "/opt/conda/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vcpuser/SDT/data_loader/loader.py", line 78, in __getitem__
    img_path_list = self.all_path[writer]
KeyError: '797'

权重的部分我是使用您提供的英文权重档，请问我是哪边出错了呢（看起来应该是有地方没有改到）？还是我应该要自己在重新训练一次而不能直接 test 呢？

谢谢您！

**Comment by dailenson** [comment]
后续我会将生成自己手写体的代码公开，并附上教程，请稍等一段时间~

**Comment by chiaoooo** [comment]
好的！謝謝您！！希望早日看到教程～
