### ISSUE TITLE
请问找不到six是什么问题

### ISSUE THREAD

**Issue by trevorcomputer** [dailenson/SDT#47]
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from parse_config import cfg, cfg_from_file, assert_and_infer_cfg
  File "E:\SDT-master\parse_config.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'
谢谢大佬！所有运行环境都配置正确

**Comment by 13232308597** [comment]
这个错误提示表明在运行 "train.py" 脚本时，缺少名为 'six' 的 Python 模块。
'six' 模块是一个用于在 Python 2 和 Python 3 之间兼容的模块。它通常用于处理一些兼容性问题。
要解决这个问题，你可以尝试以下方法：
1. 确保 'six' 模块已经安装：
   在命令指令集里输入以下命令检查 'six' 模块是否已安装：
   pip show six
   如果未安装，请使用以下命令安装 'six' 模块：
   pip install six
2.检查是否安装完成：
   pip list
   显示six在列表中且有对应版本号
   3. 检查 Python 版本兼容性：如果你同时安装了 Python 2 和 Python 3，确保在运行脚本时使用正确的 Python 版本。有时候，脚本可能依赖于特定版本的 Python，因此请确保你使用的是正确的版本。
   4. 检查模块引用路径：确保 'six' 模块所在的路径已正确添加到 Python 的模块搜索路径中。你可以在代码中添加以下行来检查和调整模块搜索路径：
   import sys
   print(sys.path)
   如果 'six' 模块所在的路径不在输出的列表中，你可以使用以下代码将其添加到搜索路径中：
   import sys
   sys.path.append('/path/to/six')
      将 '/path/to/six' 替换为 'six' 模块所在的实际路径。

**Comment by YongQI233** [comment]
挨个把提示缺少的模块都安装好，要是在国内下载慢的话可以用tuna镜像源，格式是这样：pip install six -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by YongQI233** [comment]
如果是全新环境的话大体上需要这些库：
six numpy packaging torch pyyaml easydict pillow torchvision einops lmdb opencv-python tensorboardX tqdm
另，小白一个，有不对的地方请大佬批评指正

**Comment by 13232308597** [comment]
https://www.bilibili.com/video/BV1yw411m7je/?spm_id_from=333.1007.top_right_bar_window_custom_collection.content.click
环境安装看这个系列视频就够了

**Comment by trevorcomputer** [comment]
谢谢大家

**Comment by maygyd** [comment]
我也遇到了相同的问题，并且后面还跟着一大堆包没有安装，是readme里面有什么漏掉了吗
