### ISSUE TITLE
运行训练时候报错。

### ISSUE THREAD

**Issue by 1507045** [dailenson/SDT#91]
Traceback (most recent call last):
  File "E:\SDT-master\user_generate.py", line 3, in <module>
    from parse_config import cfg, cfg_from_file, assert_and_infer_cfg
  File "E:\SDT-master\parse_config.py", line 14, in <module>
    import torch
  File "D:\Python\Python312\Lib\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\Python\Python312\Lib\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by dailenson** [comment]
python版本是多少？试下把python版本降级。可以参看下这个[WinError 126](https://blog.csdn.net/yanou1065/article/details/140712072)

**Comment by 1507045** [comment]
> python版本是多少？试下把python版本降级。可以参看下这个[WinError 126](https://blog.csdn.net/yanou1065/article/details/140712072)

改完版本后torch可以用了，但是提示必须使用NVIDIA显卡，怎么用Intel的显卡？

**Comment by xiaoxiaoli666** [comment]
> > python版本是多少？试下把python版本降级。可以参看下这个[WinError 126](https://blog.csdn.net/yanou1065/article/details/140712072)
> 
> 改完版本后torch可以用了，但是提示必须使用NVIDIA显卡，怎么用Intel的显卡？

现在深度学习都是用的cuda显卡吧？或者关闭使用gpu，都是用cpu试试？
